name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2.2.0
    - uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: nightly
          override: true
    - name: Build
      run: |
        cargo build --release --all --all-features
        mv ./target/release/cloudcafe-client ./target/release/cloudcafe-client-linux
        mv ./target/release/cloudcafe-server ./target/release/cloudcafe-server-linux
    - name: Test
      run: |
        cargo test --release --all --all-features
    - name: Upload client to S3 bucket
      uses: tpaschalis/s3-sync-action@master
      with:
        args: --acl public-read
      env:
        FILE: ./target/release/cloudcafe-client-linux
        AWS_REGION: 'eu-central-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  build-windows: 
   runs-on: windows-latest
   steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2.2.0
    - uses: actions-rs/toolchain@v1
    - uses: shallwefootball/upload-s3-action@v1.3.0
      with:
          profile: minimal
          toolchain: nightly
          override: true
    - name: Build
      run: |
        cargo build --release --package cloudcafe-client --all-features
        Rename-Item ./target/release/cloudcafe-client.exe cloudcafe-client-windows.exe
        New-Item ./target/release/client -ItemType Directory
        Copy-Item ./target/release/cloudcafe-client.exe ./target/release/client
    - name: Test
      run: |
        cargo test --release --package cloudcafe-client --all-features
    - name: Upload client to S3 bucket
      with:
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_bucket: ${{ secrets.AWS_BUCKET_NAME }}
        source_dir: ./target/release/client
        destination_dir: /
