name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2.2.0
    - name: Build Client
      uses: actions-rs/cargo@v1
      with:
        command: build -p cloudcafe-client
        args: --all-features
    - name: Build Client
      uses: actions-rs/cargo@v1
      with:
        command: build -p cloudcafe-server
        args: --all-features
    - name: Test Common
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features
    - name: Test Client
      uses: actions-rs/cargo@v1
      with:
        command: test -p cloudcafe-client
        args: --all-features
    - name: Test Server
      uses: actions-rs/cargo@v1
      with:
        command: test -p cloudcafe-server
        args: --all-features
    - name: Upload binary to S3 bucket
      uses: tpaschalis/s3-sync-action@master
      with:
        args: --acl public-read
      env:
        FILE: ./target/cloudcafe-client
        AWS_REGION: 'eu-central-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

